### PR TITLE
Add gpkg approach for reading .osm.pbf files

### PR DESCRIPTION
**Pull request by agila5**
A few lines to show the "new" approach to read `.osm.pbf` files after the discussion in #12 In the next days (and as soon as I understand #39) I will write the missing examples, docs and so on.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Looks good so far...

**Comment by agila5** [comment]
IMO the new documentation is read now. What do you think? Please flag any typo or bad english grammar. 

I can't really show the differences between the previous and current approaches because of #39 (i.e. #12 gets fixed just by adding a query parameter to sf::read_sf as in the following reprex, I don't know why). 

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

my_url <- "https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf"
sf::st_layers(my_url, do_count = TRUE) #can't read multipolygons layer
#> Warning in CPL_get_layers(dsn, options, do_count): GDAL Error 1: Too many
#> features have accumulated in lines layer. Use OGR_INTERLEAVED_READING=YES mode
#> Driver: OSM 
#> Available layers:
#>         layer_name       geometry_type features fields
#> 1           points               Point    75915     10
#> 2            lines         Line String   174369      9
#> 3 multilinestrings   Multi Line String       46      4
#> 4    multipolygons       Multi Polygon       28     25
#> 5  other_relations Geometry Collection     7902      4
sf::st_read(my_url, layer = "multipolygons", query = "select * from multipolygons")
#> Reading layer `multipolygons' from data source `https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf' using driver `OSM'
#> Simple feature collection with 443847 features and 25 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -2.189691 ymin: 53.4693 xmax: -1.180655 ymax: 53.97511
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
```

<sup>Created on 2020-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I would still apply the .gpkg approach since it was suggested by the GDAL guys. 

I would also modify the following parts if you agree: 

1. The SQL query part should be included in the ogr2ogr conversion and that should make read reading function slightly faster since the query is performed before the conversion;
2. I would change sf::read_sf to sf::st_read or document the fact that get_geofabrik and read_pbf return tbl output.

**Comment by Robinlovelace** [comment]
Hey @agila5 great work, looks good to me. Regarding your questions

> The SQL query part should be included in the ogr2ogr conversion and that should make read reading function slightly faster since the query is performed before the conversion;

Yes if it works that sounds like a good default. An argument like 'save_gpkg = FALSE` could be switched to make the `.pbf` files to `gpkg` files for future use, I was thinking, but only if that works. The read function should prefer to read in a `gpkg` file of the same name if there is one is my thinking.

Regarding 2) I suggest documenting the `tbl` output, it's more useful to have characters than factors for sure.

**Comment by agila5** [comment]
> An argument like 'save_gpkg = FALSE` could be switched to make the `.pbf` files to `gpkg` files for future use, I was thinking, but only if that works. The read function should prefer to read in a `gpkg` file of the same name if there is one is my thinking.

I didn't thought about that but it makes sense. I would also set 'save_gpkg = TRUE`  and move the vectortranslate code to get_geofabrik function so that we save only the .gpkg file instead of the .osm.pbf file. I don't see the point in saving the same file in two different formats and I would choose to save only the gpkg file. Do you agree?

**Comment by Robinlovelace** [comment]
I agree

**Comment by Robinlovelace** [comment]
Great work by the way, the PR is looking strong!

**Comment by agila5** [comment]
Yesterday I was thinking about the following idea, which is based on the previous comments. We divide the get_geofabrik function into three smaller function: the first one is used to download .osm.pbf data from geofabrik, the second one in used to translate the .osm.pbf data into .gpkg format and the third one is used to read the .gpkg format. IMO it's a reasonable approach and we could easily modify just the first function to include several providers (i.e. we should add a provider parameter, get_geofabrik becomes get_osm and so on) because of #32. 

Is that reasonable? If so I will update this PR as soon as possible. I'm super busy these days because I have to prepare a lot of materials for a Skype call at the end of the next week 😭

**Comment by Robinlovelace** [comment]
Hey @agila5 you plan sounds reasonable. Modularity is good. I fully endorse the idea of breaking the function up into 3 smaller ones that can be joined together in `get_geofabric()`, an approach that seems to work well in the function `get_stats19()`.

**Comment by Robinlovelace** [comment]
Hey @agila5 any update on this?

**Comment by agila5** [comment]
As usual I forget about these things 😅 I think I will continue on the weekend, Saturday probably, because I think it will take a few hours.

**Pull request closed without merging**
